### ISSUE TITLE
The July 4th Event

### ISSUE THREAD

**Issue by JayeHarrill** [raveconvr/pm#4]
Goal to get 5 people
Round Table Dinner Party with interesting people

- Well known enough to draw a crowd
- Hold a round table
- Talk about their passions

The Goal is to throw an event for July 4th

Given the wider world, it would be good to try and create a setting that would let the "guests" share tips and knowledge of things they can do right now.

Guests would be knowledgeable people in "new internet" things, VR, Blockchain, Mesh, Security etc

It would be a dinner party style event where people can openly talk with anyone but the idea is that with the mix of quality guest there would be a likely scenario of more quality discussions overall.

Something like a round table / dinner party format

The main moderators/hosts would stream to multiple twitch accounts with one person directing the main stream attempting to bring a singular cohesive "show" to a Twitch/youtube/etc audience.
 

**Nice to have**
- Not all in the same space

**Comment by JayeHarrill** [comment]
We each pick 1 or 2 quality guests that could be very additive to the dinner party

**Comment by lrettig** [comment]
Target ~50% existing group members, ~50% new (like a good dinner party!)
Include non-crypto types
